### ISSUE TITLE
Fire / Combat implementation

### ISSUE THREAD

**Issue by cemkoker** [cjddmut/Unity-2D-Platformer-Controller#29]
Hi, 
Nice job here ! Thank you !

Not a 'bug' but how can we implement firing action ? it would be nice to have to be a complete platformer controller !

**Comment by cjddmut** [comment]
Implementing a combat/fire into your characters wouldn't be too hard. Since Unity is very component driven, a new component can be created to handle this behavior (could also interact with the motor for dashes or knock back). 

Because of that (and the vast many different types of combat implementations) I think it would be a good project in a different github repository :)
