### ISSUE TITLE
Simulate AddForce

### ISSUE THREAD

**Issue by llafuente** [cjddmut/Unity-2D-Platformer-Controller#40]
Hi,

I working on a water bouyancy, currently I just modifying the velocity, to give the bouyancy sensation but the result is not realistic but it's ok, but i would like to try a more realistic aproach if possible. So I'm going to switching to archimedes law that ends in AddForce to the motor...

How can I simulate AddForce with the current motor code??

**Comment by cjddmut** [comment]
AddForce should work fine, will just need to look up the appropriate formulas (I'd just mimic the ones that Unity uses). To do that we'll need a concept of mass.

**Comment by shakvaal** [comment]
@cjddmut A little of the topic - why did you choose the "Transform" implementation over the "Rigidbody" in the first place? I'm making my very first 2D game atm and I'm in search of a 2D character controller, since Unity doesn't ship one. So it seems that there are only two free options: this repo and @prime32 's. Both, as I have found out inspecting the code, are written using manual transform manipulation rather than rigidbody physics. So, why?

**Comment by cjddmut** [comment]
The earlier versions were written using rigidbody but it ended up being too much of a headache. I needed to know precise information about the surrounding in order to determine things such as wall jumps, falls, and corner grabs. For example, often I would detect that we should be falling (with the box casts) but the physics system thought we were on a corner. The physics system is fantastic for getting approximate complicated physics calculations but less good for simple exact calculations. End the end it ended up being easier just to control the transform myself and allow myself to be complete authority on the state.

**Comment by shakvaal** [comment]
@cjddmut  Thank you for a detailed explaination!

**Comment by llafuente** [comment]
Closing, not using this library anymore.
