### ISSUE TITLE
Character does not move in Unity 5.3

### ISSUE THREAD

**Issue by techadmin-lightneer** [cjddmut/Unity-2D-Platformer-Controller#45]
Hi,

I just opened my project using this system in Unity 5.3 and character is not able to move while on ground. If I jump I can move but otherwise not. Also one way platforms etc does not work in 5.3

Also do you plan to add 5.3 2d effector support?

**Comment by Fabrazz** [comment]
Same issue! Any help?

**Comment by cjddmut** [comment]
I'll take a look into this issue tonight :)

I eventually plan on supported all the effectors but do not at this moment have a time table for them.

**Comment by 3noneTwo** [comment]
Definitely an issue. Weirdly, while I can't move on flat ground, I _can_ move up slopes with no problems whatsoever. Movement is super slow while moving down slopes, though.

**Comment by cjddmut** [comment]
My goal is to resolve the issue this weekend

**Comment by cjddmut** [comment]
I'm going to continue working on this but I suspect it may not be a simple fix. The Physics functions PC2D uses are now detecting collisions that otherwise used to not which is causing the platformer package to get confused and be unable to move.

I don't have a quick fix. Until I get it resolved (or maybe Unity fixes their physics functions, assuming it's a bug on their end) then the quickest resolution is to roll back to Unity 5.2.

**Comment by cjddmut** [comment]
The latest develop branch has a somewhat hacky fix pushed to it. Update to it and make sure your environment distance check increased (to about 0.08). I'll spend some time working on a better solution.

**Comment by 3noneTwo** [comment]
Appreciate the temp patch all the same, thank you!

**Comment by techadmin-lightneer** [comment]
I think everything else is now working except one way platforms. Thanks!

**Comment by cjddmut** [comment]
This should be resolved now, make sure the mininum distance from environment and environment distance checks have been increased in your own prefab.
